version: '3.8'

services:
  intellibot-core:
    build: ./IntelliBot.Core
    container_name: intellibot-core
    env_file: ./.env
    ports:
      - "5050:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 20 

  intellibot-webapp:
    build: ./IntelliBot.WebApp
    container_name: intellibot-webapp
    env_file: ./.env
    environment:
      - API_ENDPOINT=http://intellibot-core/api/cognition
    ports:
      - "5051:80"
    volumes:
      - webapp-keys:/app/keys

volumes:
  webapp-keys: