version: '3.8'

services:
  backend:
    build: ./backend
    container_name: intellibot-core
    env_file: ./.env
    ports:
      - "5050:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 30s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: intellibot-webapp
    env_file: ./.env
    ports:
      - "5051:3000"
    restart: unless-stopped

networks:
  default:
    driver: bridge